### ISSUE TITLE
zmalloc.c 126行函数名漏掉了

### ISSUE THREAD

**Issue by matrixoom** [y123456yz/middleware_development_learning#2]
void *zmalloc(size_t size)

**Comment by matrixoom** [comment]
谢谢 大佬的分享～

**Comment by y123456yz** [comment]
@571255945 
是那个demo,  这些demo只支持linux系统哈，其他系统不支持。

**Comment by matrixoom** [comment]
《异步网络框架零基础学习》 这个demo，我记得第一次clone还是好的，昨天clone的编不过了，仔细看了下，发现是zmalloc.c中的函数名没有了

**Comment by y123456yz** [comment]
@571255945  后面提交的时候误删了，已经处理了，3q
